[build-system]
requires = ["flit_core >=3.2,<4", "myst_parser==0.17.0"]
build-backend = "flit_core.buildapi"

[project]
name = "smartchartsuitedocs"
authors = [{name = "GTRI", email = "example@example.org"}]
dynamic = ["version", "description"]
